


export const SPOTIFY_REQUEST = 'SPOTIFY_REQUEST';
export const SPOTIFY_SUCCESS = 'SPOTIFY_SUCCESS';
export const SPOTIFY_FAILURE = 'SPOTIFY_FAILURE';
export const GET_TOKEN = 'GET_TOKEN';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
