


export const SPOTIFY_REQUEST = 'SPOTIFY_REQUEST';
export const SPOTIFY_SUCCESS = 'SPOTIFY_SUCCESS';
export const SPOTIFY_FAILURE = 'SPOTIFY_FAILURE';
export const GET_TOKEN = 'GET_TOKEN';
export const GET_PROFILE_IMG = 'GET_PROFILE_IMG';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';
