


export const SPOTIFY_REQUEST = 'SPOTIFY_REQUEST';
export const SPOTIFY_SUCCESS = 'SPOTIFY_SUCCESS';
export const SPOTIFY_FAILURE = 'SPOTIFY_FAILURE';
export const GET_TOKEN = 'GET_TOKEN';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
